import os
import json
import google.generativeai as genai
from pydantic import BaseModel, Field

# Define schema for the setup that Gemini must follow
class TradingSetup(BaseModel):
    ativo: str = Field(description="O ativo analisado")
    direcao_sugerida: str = Field(description="LONG, SHORT ou NEUTRAL")
    racional: str = Field(description="Explicacao unindo as metricas historicas fornecidas e o estado logico.")
    probabilidade_estatistica_hora: str = Field(description="O que a base revelou sobre esta hora especifica")
    gatilho_entrada: float = Field(description="Preco provavel para considerar o setup valido ou aproximacao de gatilho")
    stop_loss: float = Field(description="Onde o cenario seria invalidado baseado na volatilidade sugerida")

def run_gemini_setup_analyzer(api_key, profile_path, current_hour, current_price, current_mt5_rsi=None):
    genai.configure(api_key=api_key)
    
    # Using Gemini 3.1 Pro
    model = genai.GenerativeModel('gemini-3.1-pro-preview')
    
    # Load statistical profile generated by our miner
    try:
        with open(profile_path, 'r', encoding='utf-8') as f:
            profile = json.load(f)
    except FileNotFoundError:
        print(f"Erro: Arquivo {profile_path} nao encontrado. Rode o xauusd_pattern_miner.py primeiro.")
        return
        
    tod_seasonality = profile.get("time_of_day_seasonality", [])
    
    # Find statistics for the current hour
    current_hour_stats = next((item for item in tod_seasonality if item["hour"] == current_hour), None)
    
    # Construct the instruction payload
    prompt = f"""
Você é um Arquiteto Quantitativo Sênior que avalia setups combinando estatísticas passadas com eventos presentes.

MERCADO ATUAL:
Ativo: XAUUSD
Hora Atual (EET): {current_hour}h
Preço Atual Aproximado: ${current_price}
Indicador MT5 Atual (Exemplo de entrada do terminal real): RSI: {current_mt5_rsi if current_mt5_rsi else 'N/A'}

PADRÃO HISTÓRICO GERADO NOS ÚLTIMOS 5 ANOS PARA ESTA HORA ({current_hour}h):
{json.dumps(current_hour_stats, indent=2) if current_hour_stats else 'Dados insuficientes para esta hora.'}

REGIME GLOBAL (Referência de volatilidade diária média do XAUUSD):
{json.dumps(profile.get('regime_context', {}), indent=2)}

INSTRUÇÃO:
1. Examine a porcentagem de "is_bullish" e "is_bearish" para essa hora. Há um forte viés direcional na história recente?
2. Examine o "range_median" e a volatilidade média dessa hora. Se for baixa, prefira scalping de lateralização ou "NEUTRAL".
3. Estruture um setup baseado nessa pura matemática empirica.
"""

    print("Enviando contexto estatístico para o Gemini 1.5 Pro...")
    
    # Call Gemini asking for structured output
    response = model.generate_content(
        prompt,
        generation_config=genai.GenerationConfig(
            response_mime_type="application/json",
            response_schema=TradingSetup,
            temperature=0.1 # Low temperature since we want analytical precision
        )
    )
    
    print("\n--- RESPOSTA DA IA (JSON Estruturado) ---\n")
    print(response.text)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser("Gemini Setup Creator")
    parser.add_argument("--api_key", type=str, help="Sua Google Gemini API Key", default="SUA_CHAVE_AQUI")
    parser.add_argument("--profile", type=str, default="xauusd_statistical_profile.json", help="Arquivo JSON gerado pelo minerador")
    parser.add_argument("--hour", type=int, default=8, help="Hora atual EET para simular o estado")
    parser.add_argument("--price", type=float, default=2600.0, help="Preço atual aproximado do XAUUSD")
    args = parser.parse_args()
    
    key = args.api_key
    if key == "SUA_CHAVE_AQUI" and 'GEMINI_API_KEY' in os.environ:
        key = os.environ['GEMINI_API_KEY']
        
    if key == "SUA_CHAVE_AQUI":
        print("CUIDADO: Nenhuma API Key do Gemini foi configurada. Envie como argumento --api_key=XXX ou defina GEMINI_API_KEY na env.")
    else:
        run_gemini_setup_analyzer(key, args.profile, args.hour, args.price)
